# Generated by Django 3.2.15 on 2022-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_alter_category_icon_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=10000, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_path',
            field=models.FilePathField(path='static/assets/img/icons/departments/', verbose_name='символ'),
        ),
    ]
