# Generated by Django 3.2.15 on 2022-11-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_auto_20221123_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
