# Generated by Django 3.2.15 on 2022-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_auto_20221130_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=10000, verbose_name='краткое описание'),
            preserve_default=False,
        ),
    ]
