# Generated by Django 3.2.15 on 2022-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
