# Generated by Django 3.2.15 on 2022-12-08 09:30

import app_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_remove_product_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'products', 'ordering': ['name'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'ordering': ['-created_at'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='goods/no_image.jpg', upload_to=app_shop.models.get_upload_path, verbose_name='изображение'),
        ),
    ]
