# Generated by Django 3.2.15 on 2022-12-12 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0008_auto_20221208_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ProductReview',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='product_reviews',
        ),
        migrations.CreateModel(
            name='ProductViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата просмотра')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_products', to='app_shop.product', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_products', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'просмотренный товар',
                'verbose_name_plural': 'просмотренные товары',
                'db_table': 'product_viewed',
                'ordering': ['-viewed_at'],
                'default_related_name': 'viewed_products',
            },
        ),
    ]
