# Generated by Django 3.2.15 on 2022-12-13 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shop', '0009_auto_20221212_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='Review',
        ),
    ]
