# Generated by Django 3.2.15 on 2022-11-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_remove_customuser_second_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
