# Generated by Django 3.2.15 on 2022-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_remove_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='фотография профиля'),
        ),
    ]
