# Generated by Django 3.2.15 on 2022-11-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='телефон'),
        ),
    ]
