# Generated by Django 3.2.15 on 2022-12-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0008_auto_20221228_1924'),
        ('app_users', '0011_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
