# Generated by Django 3.2.15 on 2022-11-22 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0010_alter_customuser_avatar'),
        ('app_shop', '0002_alter_category_icon_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='название')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('min_order_cost', models.PositiveIntegerField(default=0, verbose_name='минимальная стоимость заказа')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'доставка',
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='стоимость')),
                ('is_paid', models.BooleanField(default=False, verbose_name='оплачено')),
                ('comment', models.TextField(max_length=5000, verbose_name='комментарий')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_users.address', verbose_name='адрес')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app_orders.delivery', verbose_name='способ доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'строка заказа',
                'verbose_name_plural': 'строки заказов',
                'db_table': 'order_items',
            },
        ),
    ]
