# Generated by Django 3.2.15 on 2022-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='min_order_cost',
            field=models.PositiveIntegerField(blank=True, verbose_name='мин. стоимость для бесплатной доставки'),
        ),
    ]
