# Generated by Django 3.2.15 on 2022-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_alter_delivery_min_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='min_order_cost',
            field=models.PositiveIntegerField(default=None, verbose_name='мин. стоимость заказа'),
        ),
    ]
