# Generated by Django 3.2.15 on 2022-12-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_alter_delivery_min_order_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_related_name': 'orders', 'ordering': ['-created_at'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
