# Generated by Django 3.2.15 on 2022-12-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
    ]
