# Generated by Django 3.2.15 on 2022-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0007_alter_delivery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='m', max_length=150, verbose_name='город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Онлайн картой'), (2, 'Онлайн со случайного чужого счёта')], default=1, verbose_name='способ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=500, verbose_name='адрес'),
        ),
    ]
