# Generated by Django 3.2.15 on 2022-12-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0008_auto_20221228_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=5000, verbose_name='комментарий'),
        ),
    ]
