# Generated by Django 3.2.15 on 2023-01-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0010_auto_20230107_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('wait', 'Ожидается оплата'), ('paid', 'Оплачен'), ('npaid', 'Не оплачен')], default='new', max_length=20, verbose_name='статус оплаты'),
        ),
    ]
