# Generated by Django 3.2.15 on 2023-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0014_auto_20230116_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait', 'Ваша оплата проверяется'), ('paid', 'Оплачен'), ('not_paid', 'Не оплачен')], default='not_paid', max_length=20, verbose_name='статус оплаты'),
        ),
    ]
